### ISSUE TITLE
Adding a task list

### ISSUE THREAD

**Issue by GymRat102** [GymRat102/typing-practice#4]
- [ ] #1 This is my first pull request
- [ ] #2 This is my second issue
- [ ] #3 This is my third issue that references the second issue

**Comment by GymRat102** [comment]
@GymRat102 is getting the hang of open-source

**Comment by GymRat102** [comment]
This comment will be turned into an issue.
